command: ["uv", "run", "start-server"]
env:
  - name: MLFLOW_TRACKING_URI
    value: "databricks"
  - name: MLFLOW_EXPERIMENT_ID
    value: "3407464201048806"
  - name: MLFLOW_TRACING_SQL_WAREHOUSE_ID
    value: "11d6beea79229431"
  - name: MLFLOW_TRACING_DESTINATION
    value: "ttan_demo_catalog_main.ai_agent_apps"
  - name: LLM_ENDPOINT_NAME
    value: "databricks-claude-3-7-sonnet"
  - name: UC_TOOL_NAMES
    value: "ttan_demo_catalog_main.ai_agent_apps.*"
  - name: VECTOR_SEARCH_INDEX
    value: "ttan_demo_catalog_main.ai_agent_apps.knowledge_base_vs_index"
  - name: VECTOR_SEARCH_ENDPOINT_NAME
    value: "dbdemos_vs_endpoint"
  - name: MCP_SERVER_URLS
    value: ""
  - name: EMBEDDING_ENDPOINT
    value: "databricks-gte-large-en"
  - name: EMBEDDING_DIMS
    value: "1024"
  - name: GENIE_ACCOUNT_SPACE_ID
    value: "01f0a40904311b03a400b5d37bca6eef"
  - name: GENIE_BILLING_SPACE_ID
    value: "01f0a408f2d11efe8212bd582d0ee08d"
  - name: LAKEBASE_AUTOSCALING_BRANCH
    value: "projects/f71d3b5c-a926-4a9d-b56f-b64aadd981e3/branches/agent-memory"
